---
- name: Bloco do teste do /usr
  block:
    - name: Verifica se a string '/usr' não consta entre os mount points
      ansible.builtin.assert:
        that: "'/usr' not in ansible_facts.mounts | map(attribute='mount')"

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_usrnaoapartado: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_usrnaoapartado: FAIL
...
