---
- name: Bloco do teste do daemon do firewalld no ar e habilitado no boot
  block:
    - name: Testa se o firewalld está no ar e habilitado no boot
      ansible.builtin.assert:
        that:
          - ansible_facts['services']['firewalld.service']['state'] == 'running'
          - ansible_facts['services']['firewalld.service']['status'] == 'enabled'

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_firewalld: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_firewalld: FAIL
...
