---

# Playbook de Health Check de SO
# Desenvolvido por Roger Príncipe (rprincip@redhat.com)

- name: RHEL Health Check
  hosts: clienterhel9.s2linux.local, clienterhel10.s2linux.local
  gather_facts: false
  vars:
    arquivo_relatorio: relatorio_{{ inventory_hostname }}.txt

  tasks:
    # TESTES DE AUTENTICAÇÃO
    - name: Verifica uso do sss no /etc/nsswitch.conf
      ansible.builtin.include_role:
        name: teste_nsswitch

    - name: Verifica conectividade com LDAP
      ansible.builtin.include_role:
        name: teste_ldap

    - name: Verifica daemon do sssd
      ansible.builtin.include_role:
        name: teste_sssd

    # TESTES DE ACESSO A CONTEÚDO
    - name: Verifica se os repositórios padrão estão ativos
      ansible.builtin.include_role:                        
        name: testerepodefaults

    - name: Verifica se é possível baixar pacotes
      ansible.builtin.include_role:
        name: testedownloadpackages

    - name: Verifica se a máquina está registrada no insights
      ansible.builtin.include_role:
        name: testeregistroinsights

    # TESTES DE LOGGING
    - name: Verifica se o daemon do rsyslog está no ar e habilitado para inicializar no boot
      ansible.builtin.include_role:                                                         
        name: testersyslog

    - name: Verifica se o rsyslog está garantindo a escrita nos arquivos de log
      ansible.builtin.include_role:                   
        name: testeescritalogs

    # SEGURANÇA
    - name: Verifica a presença de bugs
      ansible.builtin.include_role:
        name: testebugs

    - name: Verifica a presença de falhas de seguranca
      ansible.builtin.include_role:
        name: testefalhaseguranca

    - name: Verifica permissividade de execução no /tmp
      when: false
      ansible.builtin.include_role:
        name: testetmpexec

    - name: Resumo dos testes de autenticação
      ansible.builtin.set_fact:
        status_geral_auth: |
          *** AUTENTICAÇÃO ***
          Situação do nsswitch: {{ teste_nsswitch }}
          Situação da conectividade com o LDAP: {{ teste_ldap }}
          Situação do daemon do sssd: {{ teste_sssd }}

    - name: Resumo dos testes de acesso a conteúdo
      ansible.builtin.set_fact:
        status_geral_acesso_conteudo: |
          *** ACESSO A CONTEÚDO ***
          Situação dos repositórios padrão: {{ teste_repodefaults }}
          Situação de download de pacotes: {{ teste_downloadpackages }}
          Situação do registro no insights: {{ teste_registroinsights }}

    - name: Resumo dos testes de logging
      ansible.builtin.set_fact:
        status_geral_logging: |
          *** LOGGING ***
          Situação do daemon do rsyslog: {{ teste_rsyslog }}
          Situação de escrita nos logs: {{ teste_escritalogs }}

    - name: Resumo dos testes de segurança
      ansible.builtin.set_fact:
        status_geral_seguranca: |
          *** SEGURANÇA ***
          Situação de bugs: {{ teste_bugs }}
          Situação de falha de segurança: {{ teste_falhaseguranca }}

    - name: Insere as informações no relatório
      ansible.builtin.copy:       
        mode: 0644
        dest: /tmp/{{ arquivo_relatorio }}
        content: |
          {{ status_geral_auth }}
          {{ status_geral_acesso_conteudo }}
          {{ status_geral_logging }}
          {{ status_geral_seguranca }}

    - name: Traz o relatório
      ansible.builtin.fetch:
        flat: true
        src: /tmp/{{ arquivo_relatorio }}
        dest: ./
...
