---

# Playbook de Health Check de SO
# Desenvolvido por Roger Príncipe (rprincip@redhat.com)

- name: RHEL Health Check
  hosts: clienterhel10.s2linux.local, clienterhel9.s2linux.local
  gather_facts: true
  vars:
    ansible_password: 12345678
    arquivo_relatorio: relatorio_{{ inventory_hostname }}.txt

  tasks:
    # COLETA DE FACTS ADICIONAIS
    - name: Coleta os facts sobre os serviços
      tags:
        - seguranca-geral
        - rede-geral
        - lvm-geral
        - authenticacao-geral
        - miscelanea-geral
        - acesso-conteudo-geral
        - logging-geral

      ansible.builtin.service_facts:

    # TESTES DE AUTENTICAÇÃO
    - name: Verifica uso do sss no /etc/nsswitch.conf
      tags:
        - authenticacao-geral
      ansible.builtin.import_role:
        name: teste_nsswitch

    - name: Verifica conectividade com LDAP
      tags:
        - authenticacao-geral
      ansible.builtin.import_role:
        name: teste_ldap

    - name: Verifica daemon do sssd
      tags:
        - authenticacao-geral
      ansible.builtin.import_role:
        name: teste_sssd

    # TESTES DE ACESSO A CONTEÚDO
    - name: Verifica se os repositórios padrão estão ativos\
      tags:
        - acesso-conteudo-geral
      ansible.builtin.import_role:
        name: testerepodefaults

    - name: Verifica se é possível baixar pacotes
      tags:
        - acesso-conteudo-geral
      ansible.builtin.import_role:
        name: testedownloadpackages

    - name: Verifica se a máquina está registrada no insights
      tags:
        - acesso-conteudo-geral
      ansible.builtin.import_role:
        name: testeregistroinsights

    # TESTES DE LOGGING
    - name: Verifica se o daemon do rsyslog está no ar e habilitado para inicializar no boot
      tags:
        - logging-geral
      ansible.builtin.import_role:
        name: testersyslog

    - name: Verifica se o rsyslog está garantindo a escrita nos arquivos de log
      tags:
        - logging-geral
      ansible.builtin.import_role:
        name: testeescritalogs

    # TESTES DE SEGURANÇA
    - name: Verifica a presença de bugs
      tags:
        - seguranca-geral
      ansible.builtin.import_role:
        name: testebugs

    - name: Verifica a presença de falhas de seguranca
      tags:
        - seguranca-geral
      ansible.builtin.import_role:
        name: testefalhaseguranca

    - name: Verifica o audit
      tags:
        - seguranca-geral
      ansible.builtin.import_role:
        name: testeaudit

    - name: Verifica o SElinux
      tags:
        - seguranca-geral
      ansible.builtin.import_role:
        name: testeselinux

    - name: Verifica se há violações do SElinux
      tags:
        - seguranca-geral
      ansible.builtin.import_role:
        name: testeselinuxviolations

    - name: Verifica o firewalld
      tags:
        - seguranca-geral
      ansible.builtin.import_role:
        name: testefirewalld

    # TESTES DE REDE
    - name: Verifica a resolução de DNS (externa)
      tags:
        - rede-geral
      ansible.builtin.import_role:
        name: testeresolucaodnsexterno

    - name: Verifica hostname no /etc/hosts
      tags:
        - rede-geral
      ansible.builtin.import_role:
        name: testeetchosts

    - name: Verifica incremento agressivo de pacotes com erro
      tags:
        - rede-geral
      ansible.builtin.import_role:
        name: testetxrx

    - name: Verifica sincronismo com fontes NTP
      tags:
        - rede-geral
      ansible.builtin.import_role:
        name: testentp

    - name: Verifica os metadados dos VGs
      tags:
        - lvm-geral
      ansible.builtin.import_role:
        name: testemetadados

    - name: Verifica de erro em comando de LVM
      tags:
        - lvm-geral
      ansible.builtin.import_role:
        name: testeerrocomandopvs

    - name: Verifica se backup de metadados está ativo
      tags:
        - lvm-geral
      ansible.builtin.import_role:
        name: testebackupmetadados


    # TESTES - MISCELÂNEA
    - name: Verifica a coleta do sysstat
      tags:
        - miscelanea-geral
      ansible.builtin.import_role:
        name: testesar

    - name: Verifica a integridade da base RPM
      tags:
        - miscelanea-geral
      ansible.builtin.import_role:
        name: testebaserpm

    - name: Verifica a necessidade de reboot
      tags:
        - miscelanea-geral
      ansible.builtin.import_role:
        name: testerebootrequerido

    - name: Verifica se o /usr não está apartado
      tags:
        - miscelanea-geral
      ansible.builtin.import_role:
        name: testeusrnaoapartado

    - name: Verifica se o kdump está ativado
      tags:
        - miscelanea-geral
      ansible.builtin.import_role:
        name: testekdump


    # ÍNICIO DO AGRUPAMENTO DAS INFORMAÇÕES PARA EXIBIÇÃO
    - name: Resumo dos testes de autenticação
      tags:
        - authenticacao-geral
      ansible.builtin.set_fact:
        status_geral_auth: |
          *** AUTENTICAÇÃO ***
          Situação do nsswitch: {{ teste_nsswitch | default("") }}
          Situação da conectividade com o LDAP: {{ teste_ldap | default("") }}
          Situação do daemon do sssd: {{ teste_sssd | default("") }}

    - name: Resumo dos testes de acesso a conteúdo
      tags:
        - acesso-conteudo-geral
      ansible.builtin.set_fact:
        status_geral_acesso_conteudo: |
          *** ACESSO A CONTEÚDO ***
          Situação dos repositórios padrão: {{ teste_repodefaults | default("") }}
          Situação de download de pacotes: {{ teste_downloadpackages | default("") }}
          Situação do registro no insights: {{ teste_registroinsights | default("") }}

    - name: Resumo dos testes de logging
      tags:
        - logging-geral
      ansible.builtin.set_fact:
        status_geral_logging: |
          *** LOGGING ***
          Situação do daemon do rsyslog: {{ teste_rsyslog | default("") }}
          Situação de escrita nos logs: {{ teste_escritalogs | default("") }}

    - name: Resumo dos testes de segurança
      tags:
        - seguranca-geral
      ansible.builtin.set_fact:
        status_geral_seguranca: |
          *** SEGURANÇA ***
          Situação de bugs: {{ teste_bugs | default("") }}
          Situação de falha de segurança: {{ teste_falhaseguranca | default("") }}
          Situação do audit: {{ teste_audit | default("") }}
          Situação do SElinux: {{ teste_selinux | default("") }}
          Situação das violações de SElinux: {{ teste_selinuxviolations | default("") }}
          Situação do firewalld: {{ teste_firewalld | default("") }}

    - name: Resumo dos testes de rede
      tags:
        - rede-geral
      ansible.builtin.set_fact:
        status_geral_rede: |
          *** REDE ***
          Situação da resolução externa de DNS: {{ teste_resolucaodnsexterno | default("") }}
          Situação do hostname em /etc/hosts: {{ teste_etchosts | default("") }}
          Situação do incremento de pacotes com erro: {{ teste_txrx | default("") }}
          Situação do sincronismo com fontes NTP: {{ teste_ntp | default("") }}

    - name: Resumo dos testes de LVM
      tags:
        - lvm-geral
      ansible.builtin.set_fact:
        status_geral_lvm: |
          *** LVM ***
          Situação dos metadados dos VGs: {{ teste_metadados | default("") }}
          Situação de erros no comando pvs: {{ teste_errocomandopvs | default("") }}
          Situação do backup de metadados: {{ teste_backupmetadados | default("") }}

    - name: Resumo dos testes da seção de miscelanea
      tags:
        - miscelanea-geral
      ansible.builtin.set_fact:
        status_geral_miscelanea: |
          *** MISCELANEA ***
          Situação da coleta de consumo de recursos: {{ teste_sar | default("") }}
          Situação da integridade da base RPM: {{ teste_baserpm | default("") }}
          Situação da necessidade de reboot: {{ teste_rebootrequerido | default("") }}
          Situação do /usr: {{ teste_usrnaoapartado | default("") }}
          Situação do kdump: {{ teste_kdump | default("") }}

    - name: Insere as informações no relatório
      tags:
        - always
      ansible.builtin.copy:
        mode: 0644
        dest: /tmp/{{ arquivo_relatorio }}
        content: |
          {{ status_geral_auth | default("") }}
          {{ status_geral_acesso_conteudo | default("") }}
          {{ status_geral_logging | default("") }}
          {{ status_geral_seguranca | default("") }}
          {{ status_geral_rede | default("") }}
          {{ status_geral_lvm | default("") }}
          {{ status_geral_miscelanea | default("") }}

    - name: Traz o relatório
      tags:
        - always
      ansible.builtin.fetch:
        flat: true
        src: /tmp/{{ arquivo_relatorio }}
        dest: ./
...
