---
- name: Verifica uso do sss no /etc/nsswitch.conf
  block:
    - name: Captura o conteúdo do /etc/nsswitch.conf
      ansible.builtin.slurp:
        src: /etc/nsswitch.conf
      register: raw_output_nsswitch
      
    - name: Testa presença da string "sss" nos itens passwd e group
      loop:
        - passwd
        - group
      ansible.builtin.assert:
        that: "'sss' in raw_output_nsswitch['content'] | b64decode | regex_search('^{{ item }}:.*', multiline=true)"
     
    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_nsswitch: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_nsswitch: FAIL

...

