---
- name: Bloco do teste de necessidade de reboot
  block:
    - name: Faz a checagem se um reboot é necessário
      ansible.builtin.command: needs-restarting -r

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_rebootrequerido: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_rebootrequerido: FAIL
...

