---
- name: Bloco do teste de integridade da base RPM
  block:
    - name: Testa a integridade da base RPM
      ansible.builtin.command: rpm --verifydb

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_baserpm: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_baserpm: FAIL

