---
- name: Bloco do teste de erro em saída do comando pvs
  block:
    - name: executa o comando pvs
      ansible.builtin.command: pvs
      register: pvs_output

    - name: Assegura que não hajasaída de erro no comando pvs
      ansible.builtin.assert:
        that: pvs_output.stderr | length == 0

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_errocomandopvs: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_errocomandopvs: FAIL

