---
- name: Bloco do teste do SElinux
  block:
    - name: Assegura que o SELinux esteja ativado e em modo enforcing
      ansible.builtin.assert:
        that:
          - ansible_facts['selinux']['status'] == 'enabled'
          - ansible_facts['selinux']['mode'] == 'enforcing'

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_selinux: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_selinux: FAIL

