---
- name: Bloco do teste dos repositórios padrão
  block:
    - name: Lê o arquivo redhat.repo
      ansible.builtin.slurp:
        src: /etc/yum.repos.d/redhat.repo
      register: redhatrepo_output

    - name: Testa se os repositórios padrão dos RHEL 8 estão ativos
      loop:
        - '8'
        - '9'
        - '10'
      when:
        - ansible_facts['distribution_major_version'] == item
        - ansible_facts['distribution'] == 'RedHat'
      ansible.builtin.assert:
        that:
          - (redhatrepo_output['content'] | b64decode | community.general.from_ini)['rhel-' + item + '-for-x86_64-appstream-rpms'] is defined
          - (redhatrepo_output['content'] | b64decode | community.general.from_ini)['rhel-' + item + '-for-x86_64-baseos-rpms'] is defined
          - (redhatrepo_output['content'] | b64decode | community.general.from_ini)['rhel-' + item + '-for-x86_64-appstream-rpms']['enabled'] == '1'
          - (redhatrepo_output['content'] | b64decode | community.general.from_ini)['rhel-' + item + '-for-x86_64-baseos-rpms']['enabled'] == '1'

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_repodefaults: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_repodefaults: FAIL
...
