---
- name: Bloco do teste do kdump
  block:
    - name: Verifica se o kdump está ativo
      ansible.builtin.assert: {}

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_kdump: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_kdump: FAIL
...

