---
- name: Testa se é possível realizar o download de pacotes
  block:
    - name: Assegura que o yum-utils esteja instalado
      ansible.builtin.dnf:
        name: yum-utils
        state: present
        validate_certs: false

    - name: Baixa um pacote para teste
      ansible.builtin.command: yumdownloader --downloaddir /tmp httpd
      changed_when: false

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_downloadpackages: OK

  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_downloadpackages: FAIL
...
