---
- name: Bloco do teste do rsyslog no ar e habilitado no boot
  block:
    - name: Coleta os facts de serviços
      ansible.builtin.service_facts:

    - name: Testa se o daemon do rsyslog está no ar e habilitado no boot
      ansible.builtin.assert:
        that:
          - ansible_facts['services']['rsyslog.service']['state'] == "running"
          - ansible_facts['services']['rsyslog.service']['status'] == "enabled"

    - name: Considera OK para o relatório final
      ansible.builtin.set_fact:
        teste_rsyslog: OK
 
  rescue:
    - name: Considera NOK para o relatório final
      ansible.builtin.set_fact:
        teste_rsyslog: FAIL
